cleanup_ec2: don't crash on snapshot removal failures
Fixes the following exceptions as logged by
https://salsa.debian.org/cloud-admin-team/debian-cloud-images-housekeeping/-/jobs/6189025
and
https://salsa.debian.org/cloud-admin-team/debian-cloud-images-housekeeping/-/jobs/6188999

Nonexistent snapshot:
2024-08-26 16:21:41,691 INFO Deleting image 20240510-1743 from debian-sid-arm64-daily
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/__main__.py", line 32, in <module>
    main()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/__main__.py", line 28, in main
    cli.main()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/registry.py", line 119, in main
    realcls(**kw)()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/cleanup_ec2.py", line 78, in __call__
    Ec2Images(self.no_op, None, self.account, self.drivers_compute, None).cleanup(self.delete_date)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/__init__.py", line 34, in cleanup
    self._cleanup_cloud_families(families, delete_after)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/__init__.py", line 40, in _cleanup_cloud_families
    self._cleanup_cloud_versions(family.versions, delete_after, name)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/__init__.py", line 62, in _cleanup_cloud_versions
    del versions[version]
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/s2_cloud_version.py", line 60, in __delitem__
    self._children[name].delete()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/s2_cloud_version.py", line 46, in delete
    snapshot.driver.destroy_volume_snapshot(snapshot)
  File "/usr/lib/python3/dist-packages/libcloud/compute/drivers/ec2.py", line 2262, in destroy_volume_snapshot
    response = self.connection.request(self.path, params=params).object
  File "/usr/lib/python3/dist-packages/libcloud/common/base.py", line 648, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python3/dist-packages/libcloud/common/base.py", line 158, in __init__
    raise exception_from_message(code=self.status,
libcloud.common.exceptions.BaseHTTPError: InvalidSnapshot.NotFound: The snapshot 'snap-0edd292243e0643fd' does not exist.

In-use snapshot:
2024-08-26 16:04:24,596 INFO Deleting image 20240401-1704 from debian-sid-arm64-daily
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/__main__.py", line 32, in <module>
    main()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/__main__.py", line 28, in main
    cli.main()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/registry.py", line 119, in main
    realcls(**kw)()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/cli/cleanup_ec2.py", line 78, in __call__
    Ec2Images(self.no_op, None, self.account, self.drivers_compute, None).cleanup(self.delete_date)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/__init__.py", line 34, in cleanup
    self._cleanup_cloud_families(families, delete_after)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/__init__.py", line 40, in _cleanup_cloud_families
    self._cleanup_cloud_versions(family.versions, delete_after, name)
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/__init__.py", line 62, in _cleanup_cloud_versions
    del versions[version]
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/s2_cloud_version.py", line 60, in __delitem__
    self._children[name].delete()
  File "/builds/cloud-admin-team/debian-cloud-images-housekeeping/tools/src/debian_cloud_images/images/ec2/s2_cloud_version.py", line 46, in delete
    snapshot.driver.destroy_volume_snapshot(snapshot)
  File "/usr/lib/python3/dist-packages/libcloud/compute/drivers/ec2.py", line 2262, in destroy_volume_snapshot
    response = self.connection.request(self.path, params=params).object
  File "/usr/lib/python3/dist-packages/libcloud/common/base.py", line 648, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python3/dist-packages/libcloud/common/base.py", line 158, in __init__
    raise exception_from_message(code=self.status,
libcloud.common.exceptions.BaseHTTPError: InvalidSnapshot.InUse: The snapshot snap-0eef116f8d4255e69 is currently in use by ami-04e9a77da41b02259, including some disabled AMIs.